GET http://localhost:3000

###
POST http://localhost:3000/user/register
Content-Type: application/json

{   
    "USER_NAME": "Hung",
    "USER_PHONE":"0767822812",
    "USER_EMAIL": "Hung12@gmail.com",
    "USER_PASSWORD": "123456"
}
###
POST http://localhost:3000/user/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMjgsImlhdCI6MTY5NTk2NTQ4NSwiZXhwIjoxNzI3NTIzMDg1fQ.WYfQ5f1YafEXa71pqXB1PhU24gPRhOB8aOel0Vzs_kU"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{   
 
    "USER_EMAIL": "hungdz@gmail.com",
    "USER_PASSWORD": "123456"
}
###
DELETE http://localhost:3000/user/logout 
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMjgsImlhdCI6MTY5NTk2NTQ4NSwiZXhwIjoxNzI3NTIzMDg1fQ.WYfQ5f1YafEXa71pqXB1PhU24gPRhOB8aOel0Vzs_kU"
}

###
GET http://localhost:3000/user/getlists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUwMTAsImlhdCI6MTY5NjAxMDc1NSwiZXhwIjoxNjk2MDE3OTU1fQ.Cs8H2lsvw_49UmZzv-84NaRkDPFhaiDI1XgVVlTHBtc

###
GET http://localhost:3000/user/getSaveLogin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUwMTAsImlhdCI6MTY5NjAxMDc1NSwiZXhwIjoxNjk2MDE3OTU1fQ.Cs8H2lsvw_49UmZzv-84NaRkDPFhaiDI1XgVVlTHBtc
