GET http://localhost:3000

###
POST  http://localhost:3000/cart/create-cart
Content-Type: application/json

{
    "USER_ID": 10017,
    "FOOD_ID": 1024,
    "QUANTITY": 2
}

###
GET http://localhost:3000/cart/get-cart/10017

###
PATCH http://localhost:3000/cart/update-quantity/10017/1027
Content-Type: application/json

{
    "QUANTITY": 7
}

###
DELETE  http://localhost:3000/cart/delete-cart/10017
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMDE3LCJpc1Jlc3RhdXJhbnQiOmZhbHNlLCJpYXQiOjE2OTkwMTY3MzMsImV4cCI6MTY5OTAyMzkzM30.O2XXw0SjJuPsaVVap58AtgTXgs_hrggcH913HCTOMkw

