GET http://localhost:3000

###
GET http://localhost:3000/food/get-all



###
POST  http://localhost:3000/food/create-food
Content-Type: multipart/form-data

{
    "FOOD_NAME": "food",
    "FOOD_INFO": "hello",
    "FOOD_PRICE": 300,
    "FOOD_QUANTITY": 200,
    "CATEGORY": "huhu"
}

###
GET  http://localhost:3000/food/getById/1024

###
GET  http://localhost:3000/foods/search?search=Burger222222

###
GET http://localhost:3000/food/search/?search=Burger%20loại%201

###
GET http://localhost:3000/food/search?search=Burger

###
DELETE http://localhost:3000/food/delete-food/2058
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcwMTQsImlzUmVzdGF1cmFudCI6dHJ1ZSwiaWF0IjoxNjk3MTM5NjYwLCJleHAiOjE2OTcxNDY4NjB9.yDFmxst9LXM4WzmWxx6sD91rc9GkkW-RijCR1gslx2Y





