GET http://localhost:3000

###
POST http://localhost:3000/user/register
Content-Type: application/json

{   
    "USER_NAME": "Hung admin",
    "USER_PHONE":"07678522842",
    "USER_EMAIL": "Hung12@gmail.com",
    "USER_PASSWORD": "123456",
    "USER_IS_RESTAURANT": "1"
}
###
POST http://localhost:3000/user/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMjgsImlhdCI6MTY5NTk2NTQ4NSwiZXhwIjoxNzI3NTIzMDg1fQ.WYfQ5f1YafEXa71pqXB1PhU24gPRhOB8aOel0Vzs_kU"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{   
 
    "USER_EMAIL": "hung12@gmail.com",
    "USER_PASSWORD": "123456"
}
###
DELETE http://localhost:3000/user/logout 
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUwMTAsImlhdCI6MTY5NjA5OTY3MywiZXhwIjoxNzI3NjU3MjczfQ._Ep6XsH628OiqzrxzF2HCV9aovPVEn9kA-wiqmqQY9g"
}

###
GET http://localhost:3000/user/getlists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjkwMTQsImlzUmVzdGF1cmFudCI6ZmFsc2UsImlhdCI6MTY5NzAwNzU2MSwiZXhwIjoxNjk3MDE0NzYxfQ.cgRa-9gozGMuwYfZA03siE7h3jHVWuRC9wABfPGf3BM

###
GET http://localhost:3000/user/getSaveLogin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjkwMTQsImlzUmVzdGF1cmFudCI6ZmFsc2UsImlhdCI6MTY5NzAwNzU2MSwiZXhwIjoxNjk3MDE0NzYxfQ.cgRa-9gozGMuwYfZA03siE7h3jHVWuRC9wABfPGf3BM

###
POST  http://localhost:3000/user/protected-route
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcwMTQsImlzUmVzdGF1cmFudCI6dHJ1ZSwiaWF0IjoxNjk3MDU2NDc2LCJleHAiOjE2OTcwNzA4NzZ9.6qW3HNafofM85Wn54i4VXPVcmhp14aU5AHIasYudcNo


###
GET http://localhost:3000/user/getById/10017

###
PUT http://localhost:3000/user/updatePassword/10017
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMDE3LCJpc1Jlc3RhdXJhbnQiOmZhbHNlLCJpYXQiOjE2OTcxMTAwOTUsImV4cCI6MTY5NzEyNDQ5NX0.3zalokl6jA6VuFdRuPkNteOLHMYAX9Yt2RAZ9LrOFtc
Content-Type: application/json

{
    "USER_PASSWORD": "123456",
    "NEW_USER_PASSWORD": "123123"
}

    
